
@base_url = http://localhost:8000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyMTE1MTcxLCJpYXQiOjE3MzIxMTQ4NzEsImp0aSI6IjIyMTRiMzMxNzM1MDRhMTM4MzhiM2UzZDQ3NDdlYjcwIiwidXNlcl9pZCI6MX0.K0IJna2rYpVrsgYXeingjR7Eps3sbKXZhTqFVG3r6_Q

###

GET {{base_url}}/events/
Authorization: Bearer {{token}}



###
#  Obtenir mon JWT
POST {{base_url}}/token/
Content-Type: application/json

{
    "username": "bob",
    "password": "bob123456"
}


###
POST {{base_url}}/events/
Content-Type: application/json

{
    "name": "Conférence",
    "location": "Paris",
    "date": "2024-11-20",
    "description": "Conference tech",
    "max_participants": 2
}


###
PUT {{base_url}}/events/2/
Content-Type: application/json

{
    "name": "pas une fete",
    "location": "pas ici",
    "date": "2024-11-20",
    "description": "sniff c'est plus la fete"
}

###
DELETE {{base_url}}/events/5/


###
POST {{base_url}}/participants/
Content-Type: application/json

{
    "event": 9,
    "name": "Part 1",
    "email": "bob@bob.bob"
}